stages:
  - build
  - test
  - analyze
  - sync
  - package-docker

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository
    - .sonar/cache
  policy: pull-push

compilation:
  stage: build
  image: maven:3-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
      - target/classes/
    expire_in: 1 hour

unit-tests:
  stage: test
  image: maven:3-eclipse-temurin-21
  dependencies:
    - compilation
  script:
    - mvn test -Dspring.profiles.active=test
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
    reports:
      junit: target/surefire-reports/TEST-*.xml

sonarqube-check:
  stage: analyze
  image: maven:3-eclipse-temurin-21
  dependencies:
    - compilation
    - unit-tests
  script:
    - mvn sonar:sonar -Dspring.profiles.active=test -Dsonar.qualitygate.wait=true
  allow_failure: false

github-mirror:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add git
  script:
    - git push --force https://oauth2:${GITHUB_TOKEN}@github.com/Hakurunai/covoit.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}
  only:
    - main
    - develop
  dependencies:
    - sonarqube-check


# Docker avec KANIKO (Pas de dind, pas de privilèges requis)
docker-build:
  stage: package-docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  cache: [ ]
  dependencies:
    - compilation
  script:
    # Création du fichier de config pour s'authentifier au registre GitLab
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    # Construction et Push de l'image
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
  only:
    - main
    - develop