# @formatter:off

spring.datasource.url=jdbc:postgresql://database:5432/${DB_NAME}

spring.jpa.hibernate.ddl-auto=validate


# Configuration SMTP for Resend
spring.mail.host=${MAIL_HOST_PROD}
spring.mail.port=${MAIL_PORT_PROD}
spring.mail.username=${MAIL_USER_PROD}
spring.mail.password=${MAIL_PASS_PROD}
# Security ON
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true


# @formatter:on
