spring.application.name=S4_CovoitMobile

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
covoit.app.jwtSecret=${JWT_SECRET}
covoit.app.jwtExpirationMs=${JWT_EXPIRATION}
covoit.app.jwtRefreshExpiration=${JWT_REFRESH_EXPIRATION}