# @formatter:off
spring.application.name=S4_CovoitMobile

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

covoit.app.defaultAdminEmail=${DEFAULT_ADMIN_MAIL}
covoit.app.defaultAdminPassword=${DEFAULT_ADMIN_PASSWORD}

covoit.app.jwtSecret=${JWT_SECRET}
covoit.app.jwtExpirationMs=${JWT_EXPIRATION}
covoit.app.jwtRefreshExpiration=${JWT_REFRESH_EXPIRATION}


# Configuration SMTP for Mailpit
spring.mail.host=${MAIL_HOST_DEV}
spring.mail.port=${MAIL_PORT_DEV}
spring.mail.username=${MAIL_USER_DEV}
spring.mail.password=${MAIL_PASS_DEV}
# no security in local
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
# Custom var
app.mail.from=${MAIL_FROM_PROD}
app.mail.test-recipient=${MAIL_TEST_RECIPIENT}


logging.file.name=logs/api-auth.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{userId}] %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss} %-5level [%X{userId}] %logger{20} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=5

# @formatter:on